### ISSUE TITLE
unable to locate package dnsmasq

### ISSUE THREAD

**Issue by deanseiyaa** [Krutyi-4el/MyDNS#6]
$ pkg search dnsmasq
Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://dl.bintray.com/termux/termux-packages-24: bad
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
[*] https://termux.mentality.rip/termux-packages-24: ok
Picking mirror: https://termux.mentality.rip/termux-packages-24
Sorting... Done
Full Text Search... Done
$ pkg install dnsmasq
Checking availability of current mirror: ok
Reading package lists... Done
Building dependency tree... Done
E: Unable to locate package dnsmasq

**Comment by solaluset** [comment]
Have you run `pkg install root-repo`?

**Comment by AngusLkc** [comment]
It is recommended to use the system's built-in dnsmasq program
"$(which dnsmasq)"
or
"/system/bin/dnsmasq"

**Comment by solaluset** [comment]
@AngusLkc why is it recommended to do so? For me system dnsmasq caused 100% CPU usage, that's why I've set up Termux dnsmasq. Are there any issues with it?
